import Foundation
import SwiftParser
import SwiftSyntax

// Usage: SyncGen [--output <path>] <source-file...>
//
// Reads each source file, finds // @sync-annotated async functions, generates their
// synchronous peers and writes the result to --output (or stdout).

var argList = CommandLine.arguments.dropFirst()
var outputPath: String?
var inputPaths: [String] = []

var idx = argList.startIndex
while idx < argList.endIndex {
    let arg = argList[idx]
    if arg == "--output" {
        argList.formIndex(after: &idx)
        guard idx < argList.endIndex else {
            fputs("error: --output requires an argument\n", stderr)
            exit(1)
        }
        outputPath = argList[idx]
    } else {
        inputPaths.append(arg)
    }
    argList.formIndex(after: &idx)
}

guard !inputPaths.isEmpty else {
    fputs("usage: SyncGen [--output <path>] <source-file...>\n", stderr)
    exit(1)
}

// Collect peers from every input file.
var allPeers: [GeneratedPeer] = []
for path in inputPaths {
    let source: String
    do {
        source = try String(contentsOfFile: path, encoding: .utf8)
    } catch {
        fputs("error: cannot read \(path): \(error)\n", stderr)
        exit(1)
    }
    let tree = Parser.parse(source: source)
    let collector = SyncFunctionCollector()
    collector.walk(tree)
    allPeers.append(contentsOf: collector.peers)
}

// Group peers by type path, preserving first-seen order.
var typePathOrder: [String] = []
var peersByType: [String: [FunctionDeclSyntax]] = [:]
for peer in allPeers {
    if peersByType[peer.typePath] == nil {
        typePathOrder.append(peer.typePath)
        peersByType[peer.typePath] = []
    }
    peersByType[peer.typePath]!.append(peer.function)
}

// Build output.
var output = """
    // Generated by tools/SyncGen — do not edit manually.
    // To regenerate:
    //   swift run --package-path tools/SyncGen SyncGen \\
    //       Sources/Rego/VM.swift Sources/Rego/VM+Instructions.swift \\
    //       Sources/Rego/Engine.swift Sources/Rego/IREvaluator.swift \\
    //       --output Sources/Rego/Generated/SyncPeers.swift

    import AST
    import Bytecode
    import typealias IR.Local

    """

for typePath in typePathOrder {
    guard let funcs = peersByType[typePath], !funcs.isEmpty else { continue }
    output += "\nextension \(typePath) {\n"
    for f in funcs {
        output += "\n\(f.description)\n"
    }
    output += "}\n"
}

if let outPath = outputPath {
    let url = URL(fileURLWithPath: outPath)
    do {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(), withIntermediateDirectories: true)
        try output.write(to: url, atomically: true, encoding: .utf8)
        fputs("Generated \(outPath)\n", stderr)
    } catch {
        fputs("error: cannot write \(outPath): \(error)\n", stderr)
        exit(1)
    }
} else {
    print(output)
}
