import AST
import Foundation
import IR
import Testing

@testable import Rego

@Suite("MiniPlannerTests")
struct MiniPlannerTests {
    // Each plan generated by MiniPlanner has a fixed scaffolding (the
    // {"result": x} wrapper plus a result-set entry) that adds five
    // statements regardless of path length: AssignVar, MakeObject,
    // ObjectInsert, ResultSetAdd, plus one AssignVarOnce that moves the
    // walked value into local 2.
    private static let wrapperStmtCount = 5

    @Test("bare `data` query: no DotStmts, plan named `data`")
    func bareData() throws {
        let policy = try MiniPlanner.generate(query: "data")
        let plan = try #require(policy.plans?.plans.first)
        #expect(policy.plans?.plans.count == 1)
        #expect(plan.name == "data")

        // Strings table has only the wrapper key; no segments contribute.
        let strings = try #require(policy.staticData?.strings)
        #expect(strings.map(\.value) == ["result"])

        let stmts = plan.blocks[0].statements
        #expect(stmts.count == Self.wrapperStmtCount)
        // First statement copies the data root (local 1) directly into the
        // result-staging local (2); no walking happens.
        guard case .assignVarOnceStmt(let s) = stmts[0] else {
            Issue.record("expected first stmt to be AssignVarOnce")
            return
        }
        #expect(s.target == 2)
        if case .localIndex(let v) = s.source.value { #expect(v == 1) }
    }

    @Test("single segment query: one DotStmt, segment in string table")
    func singleSegment() throws {
        let policy = try MiniPlanner.generate(query: "data.foo")
        let plan = try #require(policy.plans?.plans.first)
        #expect(plan.name == "foo")

        let strings = try #require(policy.staticData?.strings)
        #expect(strings.map(\.value) == ["result", "foo"])

        let stmts = plan.blocks[0].statements
        let dotCount = stmts.filter {
            guard case .dotStmt = $0 else { return false }
            return true
        }.count
        #expect(dotCount == 1)
    }

    @Test("multi-segment query: one DotStmt per segment, in order")
    func multiSegment() throws {
        let policy = try MiniPlanner.generate(query: "data.a.b.c")
        let plan = try #require(policy.plans?.plans.first)
        #expect(plan.name == "a/b/c")

        let strings = try #require(policy.staticData?.strings)
        #expect(strings.map(\.value) == ["result", "a", "b", "c"])

        let stmts = plan.blocks[0].statements
        let dots = stmts.compactMap { stmt -> IR.DotStatement? in
            guard case .dotStmt(let s) = stmt else { return nil }
            return s
        }
        #expect(dots.count == 3)

        // Verify the chain: each Dot's source is the previous Dot's target,
        // and the key string indices walk 1, 2, 3 in order.
        var expectedSrc = 5  // local 5 holds the data root after the first AssignVarOnce
        for (i, dot) in dots.enumerated() {
            if case .localIndex(let v) = dot.source.value {
                #expect(v == expectedSrc, "dot[\(i)].source")
            } else {
                Issue.record("dot[\(i)].source not a local")
            }
            if case .stringIndex(let v) = dot.key.value {
                #expect(v == i + 1, "dot[\(i)].key index")
            } else {
                Issue.record("dot[\(i)].key not a stringIndex")
            }
            expectedSrc = Int(dot.target)
        }
    }

    @Test("non-data-prefixed query throws unsupportedQuery")
    func unsupportedQuery() throws {
        #expect {
            _ = try MiniPlanner.generate(query: "input.foo")
        } throws: { error in
            guard let regoError = error as? Rego.RegoError else { return false }
            return regoError.code == .unsupportedQuery
        }
    }
}
